name: "Create SBOM"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-22.04
    permissions:
      packages: read
    steps:
      - uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}:latest
          registry-username: ${{ github.repository_owner }}
          registry-password: ${{ github.token }}
          dependency-snapshot: true
